# Generated by Django 3.0.7 on 2020-06-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce3', '0001_initial'),
        ('ecommerce2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce3.Cohort'),
        ),
    ]
