# Generated by Django 3.0.7 on 2020-06-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce2', '0002_project_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='dead_line',
        ),
    ]
