# Generated by Django 3.0.7 on 2020-06-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce2', '0003_auto_20200628_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asign',
            new_name='assign',
        ),
    ]
