# Generated by Django 3.0.7 on 2020-06-28 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('found_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Cohorts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='core/avatar/blank_profile.png', upload_to='core/avatar')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce3.Cohort')),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='ecommerce3.UserProfile')),
                ('project', models.ManyToManyField(blank=True, to='ecommerce2.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='ecommerce3.UserProfile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_invites', to='ecommerce3.UserProfile')),
            ],
        ),
    ]
